- name: 
  hosts: web
  become: yes
  vars_prompt:
   - name: mysql_root_password
     prompt: please enter root password
     private: no
  vars: 
   login_host: db.nettam.online

  tasks: 
  - name: install mysql server
    ansible.builtin.dnf:
     name: mysql-server
     state: latest

  - name: start and enable my sql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9 # pip3.11 if python version is 3.11

  - name: check the db connection
    community.mysql.mysql_db:
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: "{{ db.nettam.online }}"
     filter: version
     ignore_error: true
    register: mysql_connection_output
    
  - name: set db root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true


      