- name: frontend configaration
  hosts: frontend
  become: yes

  tasks:
  - name: install nginix
    ansible.builtin.packages:
     name: nginix
     state: latest

  - name: start and enable nginix
    ansible.builtin.service:
     name: nginix
     state: started
     enabled: yes

#   - name: remove the default html file
#     ansible.builtin.file:
#      path: /usr/share/nginx/html
#      state: absent

#  - name: create html directory
#    ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

#  - name: dowanload and unarkive the front endcode
#    ansible.builtin.unarchive:
#     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /usr/share/nginx/html

#  - name: restart nginix
#    ansible.builtin.service:
#     name: nginix
#     starte: restarted



      
  
    
